#!/bin/bash
set -euo pipefail

# XRPL Validator Deployment Script
# Deploys a hardened rippled validator to Contabo

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TERRAFORM_DIR="${SCRIPT_DIR}/terraform"
DOCKER_DIR="${SCRIPT_DIR}/docker"
SCRIPTS_DIR="${SCRIPT_DIR}/scripts"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

check_prerequisites() {
    log_info "Checking prerequisites..."
    
    local missing_tools=()
    
    if ! command -v terraform &> /dev/null; then
        missing_tools+=("terraform")
    fi
    
    if ! command -v ssh &> /dev/null; then
        missing_tools+=("ssh")
    fi
    
    if ! command -v ssh-keygen &> /dev/null; then
        missing_tools+=("ssh-keygen")
    fi
    
    if [ ${#missing_tools[@]} -gt 0 ]; then
        log_error "Missing required tools: ${missing_tools[*]}"
        log_info "Install with: brew install ${missing_tools[*]}"
        exit 1
    fi
    
    log_info "✓ Prerequisites check passed"
}

setup_api_key() {
    log_info "Setting up Contabo API credentials..."
    
    if [ -f "${TERRAFORM_DIR}/.envrc" ]; then
        log_info "✓ .envrc file already exists"
        return 0
    fi
    
    echo ""
    log_warn "Contabo API credentials required"
    log_info "Get from: https://my.contabo.com/api/details"
    echo ""
    
    read -p "Client ID: " -r client_id
    read -p "Client Secret: " -r client_secret
    read -p "API User (email): " -r api_user
    read -sp "API Password: " -r api_password
    echo ""
    
    if [ -z "$client_id" ] || [ -z "$client_secret" ] || [ -z "$api_user" ] || [ -z "$api_password" ]; then
        log_error "All credentials required"
        exit 1
    fi
    
    # Show what was parsed
    echo "Parsed: $client_id / $client_secret / $api_user / ****"
    echo ""
    
    log_info "Creating .envrc file..."
    cat > "${TERRAFORM_DIR}/.envrc" <<EOF
# Contabo API Configuration
# Generated on $(date)

export CONTABO_CLIENT_ID="${client_id}"
export CONTABO_CLIENT_SECRET="${client_secret}"
export CONTABO_API_USER="${api_user}"
export CONTABO_API_PASSWORD="${api_password}"

export TF_VAR_contabo_client_id="\${CONTABO_CLIENT_ID}"
export TF_VAR_contabo_client_secret="\${CONTABO_CLIENT_SECRET}"
export TF_VAR_contabo_api_user="\${CONTABO_API_USER}"
export TF_VAR_contabo_api_password="\${CONTABO_API_PASSWORD}"
EOF
    
    chmod 600 "${TERRAFORM_DIR}/.envrc"
    log_info "✓ Credentials saved to ${TERRAFORM_DIR}/.envrc"
}

generate_ssh_key() {
    log_info "SSH keys auto-generated by Terraform"
}

terraform_init() {
    log_info "Initializing Terraform..."
    
    cd "${TERRAFORM_DIR}"
    source .envrc
    
    terraform init
    log_info "✓ Terraform initialized"
}

terraform_plan() {
    log_info "Planning infrastructure..."
    
    cd "${TERRAFORM_DIR}"
    source .envrc
    
    terraform plan -out=tfplan
    log_info "✓ Infrastructure plan created"
}

terraform_apply() {
    log_info "Deploying infrastructure to Contabo..."
    
    cd "${TERRAFORM_DIR}"
    source .envrc
    
    terraform apply tfplan
    rm -f tfplan
    
    log_info "✓ Infrastructure deployed"
}

get_validator_ip() {
    cd "${TERRAFORM_DIR}"
    terraform output -raw validator_ip
}

wait_for_ssh() {
    local ip=$1
    local max_attempts=30
    local attempt=0
    
    log_info "Waiting for SSH to become available..."
    
    while [ $attempt -lt $max_attempts ]; do
        if ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 \
               -i "${TERRAFORM_DIR}/validator_ssh_key" \
               root@"${ip}" "echo 'SSH ready'" &> /dev/null; then
            log_info "✓ SSH connection established"
            return 0
        fi
        
        attempt=$((attempt + 1))
        echo -n "."
        sleep 10
    done
    
    log_error "SSH connection timeout"
    return 1
}

setup_vm() {
    local ip=$1
    log_info "Setting up and hardening VM..."
    
    # Copy setup scripts
    scp -i "${TERRAFORM_DIR}/validator_ssh_key" \
        "${SCRIPTS_DIR}/setup-vm.sh" \
        "${SCRIPTS_DIR}/install-docker.sh" \
        root@"${ip}":/tmp/
    
    # Execute setup
    ssh -i "${TERRAFORM_DIR}/validator_ssh_key" root@"${ip}" \
        "bash /tmp/setup-vm.sh && bash /tmp/install-docker.sh"
    
    log_info "✓ VM setup complete"
}

deploy_rippled() {
    local ip=$1
    log_info "Deploying rippled container..."
    
    # Copy Docker configuration
    ssh -i "${TERRAFORM_DIR}/validator_ssh_key" root@"${ip}" \
        "mkdir -p /opt/rippled"
    
    scp -i "${TERRAFORM_DIR}/validator_ssh_key" \
        "${DOCKER_DIR}/docker-compose.yml" \
        "${DOCKER_DIR}/rippled.cfg" \
        root@"${ip}":/opt/rippled/
    
    # Start rippled
    ssh -i "${TERRAFORM_DIR}/validator_ssh_key" root@"${ip}" \
        "cd /opt/rippled && docker-compose up -d"
    
    log_info "✓ rippled container deployed"
}

wait_for_rippled() {
    local ip=$1
    local max_attempts=60
    local attempt=0
    
    log_info "Waiting for rippled to be ready..."
    
    while [ $attempt -lt $max_attempts ]; do
        # Check if container is running (not restarting)
        if ssh -i "${TERRAFORM_DIR}/validator_ssh_key" root@"${ip}" \
               "docker ps --filter name=rippled --filter status=running | grep -q rippled" 2>/dev/null; then
            # Container is running, check if rippled is responding
            if ssh -i "${TERRAFORM_DIR}/validator_ssh_key" root@"${ip}" \
                   "docker exec rippled /opt/ripple/bin/rippled server_info" &>/dev/null; then
                log_info "✓ rippled is ready"
                return 0
            fi
        fi
        
        attempt=$((attempt + 1))
        echo -n "."
        sleep 5
    done
    
    log_error "rippled failed to start properly"
    log_info "Check logs with: ssh -i terraform/validator_ssh_key root@${ip} 'docker logs rippled'"
    return 1
}

generate_validator_keys() {
    log_info "Generating validator keys..."
    log_warn "IMPORTANT: Validator keys should be generated offline for production"
    log_info "For this deployment, keys will be generated on the server"
    
    local ip=$(get_validator_ip)
    
    # Generate validator keys using rippled's built-in command
    local keys_output=$(ssh -i "${TERRAFORM_DIR}/validator_ssh_key" root@"${ip}" \
        "docker exec rippled /opt/ripple/bin/rippled validation_create")
    
    echo "$keys_output"
    
    # Extract public key and secret from output
    # Output format:
    # {
    #    "status" : "success",
    #    "validation_key" : "FOLD WERE NORM ...",
    #    "validation_public_key" : "n9L...",
    #    "validation_seed" : "ss..."
    # }
    
    local pubkey=$(echo "$keys_output" | jq -r '.result.validation_public_key')
    local secret=$(echo "$keys_output" | jq -r '.result.validation_seed')
    
    if [ -z "$pubkey" ] || [ "$pubkey" = "null" ]; then
        log_error "Failed to extract validator keys"
        echo "$keys_output"
        exit 1
    fi
    
    log_info "✓ Validator keys generated"
    log_warn "IMPORTANT: Save these keys securely!"
    echo ""
    echo "Validation Public Key: ${pubkey}"
    echo "Validation Seed: ${secret}"
    echo ""
    
    # Configure validator
    configure_validator "$ip" "$pubkey" "$secret"
}

configure_validator() {
    local ip=$1
    local pubkey=$2
    local secret=$3
    
    log_info "Configuring validator with generated keys..."
    
    # Validate inputs
    if [ -z "$secret" ] || [ "$secret" = "null" ]; then
        log_error "Invalid validation seed - cannot configure validator"
        exit 1
    fi
    
    if [ -z "$pubkey" ] || [ "$pubkey" = "null" ]; then
        log_error "Invalid public key - cannot configure validator"
        exit 1
    fi
    
    # Add validation_seed section to config
    ssh -i "${TERRAFORM_DIR}/validator_ssh_key" root@"${ip}" "cat >> /opt/rippled/rippled.cfg << 'EOF'

# Validator Configuration (auto-configured during deployment)
[validation_seed]
EOF
echo '${secret}' | ssh -i '${TERRAFORM_DIR}/validator_ssh_key' root@'${ip}' 'cat >> /opt/rippled/rippled.cfg'"
    
    log_info "✓ Validator configuration added"
    log_info "Public key: ${pubkey}"
    
    # Restart rippled to apply validator config
    log_info "Restarting rippled to enable validation..."
    ssh -i "${TERRAFORM_DIR}/validator_ssh_key" root@"${ip}" \
        "cd /opt/rippled && docker-compose restart"
    
    wait_for_rippled "${ip}"
    
    log_info "✓ Validator configured and running"
}

show_completion_info() {
    local ip=$(get_validator_ip)
    
    echo ""
    log_info "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    log_info "🎉 XRPL Validator Deployment Complete!"
    log_info "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    log_info "Validator IP: ${ip}"
    log_info "SSH Access:   ssh -i terraform/validator_ssh_key root@${ip}"
    echo ""
    log_info "Quick Commands:"
    log_info "  make ssh       - SSH into validator"
    log_info "  make status    - Check validator status"
    log_info "  make logs      - View rippled logs"
    log_info "  make health    - Health check"
    echo ""
    log_info "Next Steps:"
    log_info "  1. Save your validator keys (shown above)"
    log_info "  2. Add validator public key to UNL"
    log_info "  3. Monitor with: make status"
    log_info "  4. Check logs with: make logs"
    echo ""
    log_warn "Remember to backup your validator keys offline!"
    log_info "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
}

main() {
    log_info "Starting XRPL Validator Deployment"
    log_info "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    
    check_prerequisites
    setup_api_key
    generate_ssh_key
    terraform_init
    terraform_plan
    
    read -p "Apply Terraform plan? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        log_warn "Deployment cancelled"
        exit 0
    fi
    
    terraform_apply
    
    local validator_ip=$(get_validator_ip)
    log_info "Validator IP: ${validator_ip}"
    
    wait_for_ssh "${validator_ip}"
    setup_vm "${validator_ip}"
    deploy_rippled "${validator_ip}"
    wait_for_rippled "${validator_ip}"
    
    generate_validator_keys
    
    show_completion_info
}

main "$@"
